print("Bienvenido a la oficina de renovación digital del DNI.")
numero_dni = input("\nIngrese su número de DNI:\n")
nombre = input("\nIngrese su nombre:\n")
apellidos = input("\nIngrese sus apellidos:\n")
fecha_de_nacimiento = input("\nIngrese su fecha de nacimiento:\n")
lugar_de_nacimiento = input("\nIngrese su localidad de nacimiento:\n")
provincia_de_nacimiento = input("\nIngrese su provincia de nacimiento:\n")
nombre_padre = input("\nIngrese el nombre de pila de su padre:\n")
nombre_madre = input("\nIngrese el nombre de su madre:\n")
dirección = input("\nIngrese su dirección donde resida actualmente:\n")
localidad_de_dirección = input("\nIngrese su localidad de residencia:\n")
provincia_de_dirección = input("\nIngrese su provincia de residencia:\n")
print(f"Su DNI " + {numero_dni} + " ha sido renovado a nombre de " + {nombre} + " " + {apellidos} + ", hijo de " + {nombre_padre} + " y " + {nombre_madre} + ", nacido el " + {fecha_de_nacimiento} + " en " + {lugar_de_nacimiento} + ", en la provincia de " + {provincia_de_nacimiento} + ", y residente en " + {dirección} + ", en la localidad de " + {localidad_de_dirección} + ", en la provincia de " + {provincia_de_dirección} + ".")